/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

/**
 *
 * @author JED
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class EDUHANCE_StudentJoinSettings extends javax.swing.JFrame {

    /**
     * Creates new form EDUHANCE_StudentJoinSettings
     */
    public EDUHANCE_StudentJoinSettings() {
        initComponents();
        
        CheckLobbyIDLength();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        titleLabel3 = new javax.swing.JLabel();
        lobbyidField = new javax.swing.JTextField();
        joinlobbyButton = new javax.swing.JButton();
        sizeStabilizerPanel = new javax.swing.JPanel();
        cancellobbyButton = new javax.swing.JButton();
        lobbyidLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("Join Lobby");
        getContentPane().add(titleLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, 132, 20));

        lobbyidField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lobbyidField.setForeground(new java.awt.Color(33, 78, 114));
        lobbyidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobbyidFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lobbyidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 103, 246, 35));

        joinlobbyButton.setBackground(new java.awt.Color(250, 250, 250));
        joinlobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        joinlobbyButton.setForeground(new java.awt.Color(5, 35, 79));
        joinlobbyButton.setText("Join");
        joinlobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joinlobbyButton.setEnabled(false);
        joinlobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinlobbyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(joinlobbyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 242, 101, 39));

        sizeStabilizerPanel.setBackground(new java.awt.Color(5, 35, 79));

        cancellobbyButton.setBackground(new java.awt.Color(255, 0, 0));
        cancellobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancellobbyButton.setForeground(new java.awt.Color(255, 255, 255));
        cancellobbyButton.setText("Cancel");
        cancellobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancellobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellobbyButtonActionPerformed(evt);
            }
        });

        lobbyidLabel.setBackground(new java.awt.Color(255, 255, 255));
        lobbyidLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lobbyidLabel.setForeground(new java.awt.Color(255, 255, 255));
        lobbyidLabel.setText("Lobby Code:");

        javax.swing.GroupLayout sizeStabilizerPanelLayout = new javax.swing.GroupLayout(sizeStabilizerPanel);
        sizeStabilizerPanel.setLayout(sizeStabilizerPanelLayout);
        sizeStabilizerPanelLayout.setHorizontalGroup(
            sizeStabilizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeStabilizerPanelLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(cancellobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(sizeStabilizerPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lobbyidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sizeStabilizerPanelLayout.setVerticalGroup(
            sizeStabilizerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeStabilizerPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lobbyidLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(cancellobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(sizeStabilizerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lobbyidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lobbyidFieldActionPerformed
        
    }//GEN-LAST:event_lobbyidFieldActionPerformed

    private void cancellobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellobbyButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancellobbyButtonActionPerformed

    private void joinlobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinlobbyButtonActionPerformed
        String inputtedLobbyCode = lobbyidField.getText();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/eduhance_db", "root", "");

            String sql = "SELECT * FROM lobby WHERE lobbyCode = ? AND lobbyStatus = 1";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, inputtedLobbyCode);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                EDUHANCE_Lobby lobby = new EDUHANCE_Lobby();
                
                int lobbyId = rs.getInt("lobbyId");
                String instructor = rs.getString("lobbyInstructor");
                String subject = rs.getString("lobbySubject");
                String section = rs.getString("lobbySection");
                String date = rs.getString("lobbyDate");
                
                String currentUserId = UserSession.getInstance().getUserId();
                System.out.println("Raw user ID: " + currentUserId);
                currentUserId = currentUserId.split(",")[0];
                System.out.println("After split by ',': " + currentUserId); 
                
                if(currentUserId.contains(":")) {
                    currentUserId = currentUserId.split(":")[1];
                    System.out.println("After split by ':': " + currentUserId);
                }
                int convertedUserId = Integer.parseInt(currentUserId);
                System.out.println("Final user ID (integer): " + convertedUserId);
                
                String insertSql = "INSERT INTO lobby_students (lobbyId, studentId, active) VALUES (?, ?, 1)";
                PreparedStatement insertStmt = conn.prepareStatement(insertSql);
                insertStmt.setInt(1, lobbyId);
                insertStmt.setInt(2, convertedUserId); // Get current student's ID
                insertStmt.executeUpdate();
                
                lobby.setLobbyCode(inputtedLobbyCode);
                lobby.setLobbyDetails(instructor, subject, section, date);
                
                lobby.setLocationRelativeTo(null);
                lobby.setVisible(true);
                this.setVisible(false);

                EDUHANCE_StudentLandingPage.instance.dispose();
                this.dispose();
            } else {

                JOptionPane.showMessageDialog(this, "Invalid lobby code or lobby is inactive!", "Join Error", JOptionPane.ERROR_MESSAGE);
            }

            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_joinlobbyButtonActionPerformed
    
    
    private void CheckLobbyIDLength(){
        lobbyidField.setDocument(new javax.swing.text.PlainDocument() {
            public void insertString(int offset, String str, javax.swing.text.AttributeSet attr) throws javax.swing.text.BadLocationException {
                if ((getLength() + str.length()) <= 8) {
                    super.insertString(offset, str, attr);
                    joinlobbyButton.setEnabled(getLength() == 8);
                } 
            }
            public void remove(int offs, int len) throws javax.swing.text.BadLocationException {
                super.remove(offs, len);
                joinlobbyButton.setEnabled(getLength() == 8);
            }
            
        });
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentJoinSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentJoinSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentJoinSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentJoinSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDUHANCE_StudentJoinSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancellobbyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton joinlobbyButton;
    private javax.swing.JTextField lobbyidField;
    private javax.swing.JLabel lobbyidLabel;
    private javax.swing.JPanel sizeStabilizerPanel;
    private javax.swing.JLabel titleLabel3;
    // End of variables declaration//GEN-END:variables
}
