/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

import java.util.Random;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;



/**
 *
 * @author JED
 */
public class EDUHANCE_CreateLobby extends javax.swing.JFrame {

    /**
     * Creates new form EDUHANCE_CreateLobby
     */
    public EDUHANCE_CreateLobby() {
        initComponents();
        
        setInstructorName();
        setDate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instructorField = new javax.swing.JTextField();
        instructorboxLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        subjectField = new javax.swing.JTextField();
        subjectboxLabel1 = new javax.swing.JLabel();
        sectionField = new javax.swing.JTextField();
        sectionboxLabel1 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        dateboxLabel2 = new javax.swing.JLabel();
        createlobbyButton = new javax.swing.JButton();
        cancellobbyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 35, 79));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 300));

        instructorField.setBackground(new java.awt.Color(250, 250, 250));
        instructorField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        instructorField.setForeground(new java.awt.Color(33, 78, 114));
        instructorField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        instructorField.setCaretColor(new java.awt.Color(51, 51, 51));
        instructorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorFieldActionPerformed(evt);
            }
        });

        instructorboxLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        instructorboxLabel2.setForeground(new java.awt.Color(250, 250, 250));
        instructorboxLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructorboxLabel2.setText("Instructor Name:");

        titleLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(250, 250, 250));
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("Create Lobby");

        subjectField.setBackground(new java.awt.Color(250, 250, 250));
        subjectField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subjectField.setForeground(new java.awt.Color(33, 78, 114));
        subjectField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        subjectField.setCaretColor(new java.awt.Color(51, 51, 51));
        subjectField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectFieldActionPerformed(evt);
            }
        });

        subjectboxLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        subjectboxLabel1.setForeground(new java.awt.Color(250, 250, 250));
        subjectboxLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subjectboxLabel1.setText("Subject:");

        sectionField.setBackground(new java.awt.Color(250, 250, 250));
        sectionField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sectionField.setForeground(new java.awt.Color(33, 78, 114));
        sectionField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        sectionField.setCaretColor(new java.awt.Color(51, 51, 51));
        sectionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionFieldActionPerformed(evt);
            }
        });

        sectionboxLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        sectionboxLabel1.setForeground(new java.awt.Color(250, 250, 250));
        sectionboxLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sectionboxLabel1.setText("Section:");

        dateField.setBackground(new java.awt.Color(250, 250, 250));
        dateField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dateField.setForeground(new java.awt.Color(33, 78, 114));
        dateField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        dateField.setCaretColor(new java.awt.Color(51, 51, 51));
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        dateboxLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dateboxLabel2.setForeground(new java.awt.Color(250, 250, 250));
        dateboxLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateboxLabel2.setText("Date:");

        createlobbyButton.setBackground(new java.awt.Color(250, 250, 250));
        createlobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        createlobbyButton.setForeground(new java.awt.Color(5, 35, 79));
        createlobbyButton.setText("Create");
        createlobbyButton.setToolTipText("");
        createlobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createlobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createlobbyButtonActionPerformed(evt);
            }
        });

        cancellobbyButton.setBackground(new java.awt.Color(255, 0, 0));
        cancellobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancellobbyButton.setForeground(new java.awt.Color(255, 255, 255));
        cancellobbyButton.setText("Cancel");
        cancellobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancellobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellobbyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(instructorboxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(instructorField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sectionboxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(sectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(subjectboxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateboxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createlobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cancellobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instructorboxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructorField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjectboxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sectionField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectionboxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateboxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createlobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancellobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createlobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createlobbyButtonActionPerformed
        EDUHANCE_InstructorLobby lobby = new EDUHANCE_InstructorLobby();
        
        String lobbyCode = generateLobbyCode();
        lobby.getLobbyCodeField().setText(lobbyCode);
        
        String instructor = instructorField.getText();
        String subject = subjectField.getText();
        String section = sectionField.getText();
        String date = dateField.getText();
        
        lobby.getInstructornameboxField1().setText(instructor);
        lobby.getSubjectboxField1().setText(subject);
        lobby.getSectionboxField1().setText(section);
        lobby.getDateboxField3().setText(date);
        
    
        lobby.setLocationRelativeTo(null);
        lobby.setVisible(true);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/eduhance_db", "root", "");

            String sql = "INSERT INTO lobby (lobbyCode, lobbyInstructor, lobbySubject, lobbySection, lobbyDate, lobbyStatus) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);

            pstmt.setString(1, lobbyCode);
            pstmt.setString(2, instructor);
            pstmt.setString(3, subject);
            pstmt.setString(4, section);
            pstmt.setString(5, date);
            pstmt.setInt(6, 1);

            pstmt.executeUpdate();

            conn.close();

            lobby.setLocationRelativeTo(null);
            lobby.setVisible(true);
            EDUHANCE_StudentLandingPage.instance.dispose();
            this.dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_createlobbyButtonActionPerformed

    private void cancellobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellobbyButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancellobbyButtonActionPerformed

    private void instructorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void subjectFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectFieldActionPerformed

    private void sectionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sectionFieldActionPerformed
    
    private void setInstructorName(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/eduhance_db", "root", "");

            String sql = "SELECT firstName, lastName from users where id = ?"; 
            PreparedStatement stmt = conn.prepareStatement(sql);

            
            String rawUserId = UserSession.getInstance().getUserId();
            String cleanUserId = rawUserId.replaceAll("[^0-9]", "");

            stmt.setString(1, cleanUserId);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                String firstName = rs.getString("firstName");
                String lastName = rs.getString("lastName");
                instructorField.setText(firstName + " " + lastName);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void setDate(){
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MM/dd/yyyy");
        java.util.Date currentDate = new java.util.Date();
        dateField.setText(sdf.format(currentDate));
    }
    
    private String generateLobbyCode() {
    String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    StringBuilder code = new StringBuilder();
    Random random = new Random();
    
    for (int i = 0; i < 8; i++) {
        code.append(characters.charAt(random.nextInt(characters.length())));
    }
    
    return code.toString();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_CreateLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_CreateLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_CreateLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_CreateLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDUHANCE_CreateLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancellobbyButton;
    private javax.swing.JButton createlobbyButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateboxLabel2;
    private javax.swing.JTextField instructorField;
    private javax.swing.JLabel instructorboxLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sectionField;
    private javax.swing.JLabel sectionboxLabel1;
    private javax.swing.JTextField subjectField;
    private javax.swing.JLabel subjectboxLabel1;
    private javax.swing.JLabel titleLabel3;
    // End of variables declaration//GEN-END:variables
}
