/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;


/**
 *
 * @author JED
 */
public class EDUHANCE_StudentLandingPage extends javax.swing.JFrame {
    public static EDUHANCE_StudentLandingPage instance;
    private Connection connection;
    private String lobbyCode;

    /**
     * Creates new form EDUHANCE_StudentLandingPage
     */
    public EDUHANCE_StudentLandingPage() {
        initComponents();
        instance = this;
        
        establishDatabaseConnection();
        
        timedateDisplay();
        loadProfilePicture();
        updateRejoinPanelVisibility();
    }
    
    private void establishDatabaseConnection() {
        try {
            connection = DatabaseConnection.getConnection();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Database connection failed", 
                "Connection Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel555 = new javax.swing.JPanel();
        signoutButton = new javax.swing.JButton();
        nameLoggedinLabel = new javax.swing.JLabel();
        emailLoggedinLabel = new javax.swing.JLabel();
        courseLoggedinLabel = new javax.swing.JLabel();
        yearlevelLoggedLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        editprofileIcon = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addfriendIcon = new javax.swing.JLabel();
        addfileIcon = new javax.swing.JLabel();
        lblProfilePic = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        datedisplayLabel = new javax.swing.JLabel();
        timedisplayLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createlobbyButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        joinButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rejoinlobbyButton = new javax.swing.JButton();
        existinglobbycodeLabel = new javax.swing.JLabel();
        existinglobbycodeLabel1 = new javax.swing.JLabel();
        rejoinlobbyButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titleLabel2.setForeground(java.awt.Color.white);
        titleLabel2.setText("EDUHANCE");
        getContentPane().add(titleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 19, -1, -1));

        titleLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleLabel3.setForeground(java.awt.Color.white);
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("Student Inquiry System");
        getContentPane().add(titleLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 59, 270, 20));

        jPanel1.setBackground(new java.awt.Color(33, 78, 114));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 4, true));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel555.setBackground(new java.awt.Color(33, 78, 114));

        signoutButton.setBackground(new java.awt.Color(139, 105, 20));
        signoutButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(255, 215, 0));
        signoutButton.setText("Sign out");
        signoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        signoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });

        nameLoggedinLabel.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        nameLoggedinLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLoggedinLabel.setText("USER");

        emailLoggedinLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        emailLoggedinLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLoggedinLabel.setText("email");

        courseLoggedinLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        courseLoggedinLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLoggedinLabel.setText("course");

        yearlevelLoggedLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        yearlevelLoggedLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearlevelLoggedLabel.setText("year level");

        jPanel3.setBackground(new java.awt.Color(33, 78, 114));
        jPanel3.setToolTipText("");

        editprofileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_property_24px.png"))); // NOI18N
        editprofileIcon.setToolTipText("Edit Profile");
        editprofileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editprofileIcon.setPreferredSize(new java.awt.Dimension(32, 32));
        editprofileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProfileEditWindow(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(editprofileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(editprofileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        addfriendIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add_user_group_woman_man_24px.png"))); // NOI18N
        addfriendIcon.setToolTipText("Add Students/Educators");
        addfriendIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addfriendIcon.setPreferredSize(new java.awt.Dimension(32, 32));
        addfriendIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addfriendIconshowEditWindow(evt);
            }
        });

        addfileIcon.setBackground(new java.awt.Color(51, 255, 51));
        addfileIcon.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        addfileIcon.setForeground(new java.awt.Color(102, 102, 102));
        addfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/google_forms_24px.png"))); // NOI18N
        addfileIcon.setToolTipText("Report Issue");
        addfileIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addfileIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openReportWindow(evt);
            }
        });

        lblProfilePic.setBackground(new java.awt.Color(0, 0, 0));
        lblProfilePic.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblProfilePic.setForeground(new java.awt.Color(255, 255, 255));
        lblProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePic.setText("DP");
        lblProfilePic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout panel555Layout = new javax.swing.GroupLayout(panel555);
        panel555.setLayout(panel555Layout);
        panel555Layout.setHorizontalGroup(
            panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel555Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel555Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addfriendIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addfileIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel555Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel555Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel555Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLoggedinLabel)
                    .addComponent(emailLoggedinLabel)
                    .addComponent(courseLoggedinLabel)
                    .addComponent(yearlevelLoggedLabel))
                .addGap(14, 14, 14))
        );
        panel555Layout.setVerticalGroup(
            panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel555Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel555Layout.createSequentialGroup()
                        .addComponent(nameLoggedinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLoggedinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseLoggedinLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearlevelLoggedLabel))
                    .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel555Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addfileIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addfriendIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(signoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panel555, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 176, 340, 320));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datedisplayLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        datedisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        datedisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datedisplayLabel.setText("DATE");
        jPanel6.add(datedisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 25));

        timedisplayLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        timedisplayLabel1.setForeground(new java.awt.Color(255, 255, 255));
        timedisplayLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(timedisplayLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 290, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eduhance_student_inquiry_system_mainfile/images/timedatebackground.jpg"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 160));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 114, 350, 500));

        createlobbyButton.setBackground(new java.awt.Color(250, 250, 250));
        createlobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        createlobbyButton.setForeground(new java.awt.Color(5, 35, 79));
        createlobbyButton.setText("<htmL>Create <br>Lobby</htmL>");
        createlobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createlobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createlobbyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createlobbyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 144, 54));

        jPanel2.setBackground(new java.awt.Color(33, 78, 114));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        joinButton.setBackground(new java.awt.Color(250, 250, 250));
        joinButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        joinButton.setForeground(new java.awt.Color(5, 35, 79));
        joinButton.setText("Join");
        joinButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });
        getContentPane().add(joinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 144, 54));

        jPanel4.setBackground(new java.awt.Color(5, 35, 79));

        jPanel7.setBackground(new java.awt.Color(33, 78, 114));

        rejoinlobbyButton.setBackground(new java.awt.Color(250, 250, 250));
        rejoinlobbyButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rejoinlobbyButton.setForeground(new java.awt.Color(5, 35, 79));
        rejoinlobbyButton.setText("Rejoin Lobby");
        rejoinlobbyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rejoinlobbyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejoinlobbyButtonActionPerformed(evt);
            }
        });

        existinglobbycodeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        existinglobbycodeLabel.setForeground(new java.awt.Color(255, 255, 255));
        existinglobbycodeLabel.setText("lobbycode");

        existinglobbycodeLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        existinglobbycodeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        existinglobbycodeLabel1.setText("Current Lobby Code:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(existinglobbycodeLabel)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(existinglobbycodeLabel1)
                            .addComponent(rejoinlobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(existinglobbycodeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existinglobbycodeLabel)
                .addGap(18, 18, 18)
                .addComponent(rejoinlobbyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        rejoinlobbyButton1.setBackground(new java.awt.Color(250, 250, 250));
        rejoinlobbyButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rejoinlobbyButton1.setForeground(new java.awt.Color(5, 35, 79));
        rejoinlobbyButton1.setText("Rejoin Lobby");
        rejoinlobbyButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rejoinlobbyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejoinlobbyButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(rejoinlobbyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(rejoinlobbyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createlobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createlobbyButtonActionPerformed
        EDUHANCE_CreateLobby createlobbywin = new EDUHANCE_CreateLobby();
        
        createlobbywin.setVisible(true);
    }//GEN-LAST:event_createlobbyButtonActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        EDUHANCE_StudentJoinSettings joinsetting = new EDUHANCE_StudentJoinSettings();
        joinsetting.setVisible(true);
    }//GEN-LAST:event_joinButtonActionPerformed

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Sign out to this account?",
            "Sign Out", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            dispose();
            LOGIN_EDH2 loginpage = new LOGIN_EDH2();
            loginpage.setVisible(true);

        }
    }//GEN-LAST:event_signoutButtonActionPerformed

    private void showProfileEditWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProfileEditWindow
        new EDUHANCE_ProfileWindow(this).setVisible(true);
    }//GEN-LAST:event_showProfileEditWindow

    private void addfriendIconshowEditWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addfriendIconshowEditWindow
        // TODO add your handling code here:
    }//GEN-LAST:event_addfriendIconshowEditWindow

    private void openReportWindow(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openReportWindow
        EDUHANCE_ReportWindow reportWin = new EDUHANCE_ReportWindow();
        reportWin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_openReportWindow

    private void rejoinlobbyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejoinlobbyButtonActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_rejoinlobbyButtonActionPerformed

    private void rejoinlobbyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejoinlobbyButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejoinlobbyButton1ActionPerformed
 
    public void setUserData(String name, String email, String course, String yearLevel) {
        nameLoggedinLabel.setText(name);
        emailLoggedinLabel.setText(maskEmail(email));
        courseLoggedinLabel.setText(course);
        yearlevelLoggedLabel.setText(yearLevel);
    }
    
    private String maskEmail(String email) {
        if (email == null || email.isEmpty()) {
            return email;
        }

        String[] parts = email.split("@");
        if (parts.length != 2) {
            return email;
        }

        String localPart = parts[0];
        String domain = parts[1];

        if (localPart.length() <= 3) {
            return email;
        }

        String maskedLocal = localPart.substring(0, 3) + 
                            "*".repeat(localPart.length() - 4) + 
                            localPart.charAt(localPart.length() - 1);

        return maskedLocal + "@" + domain;
    }
    
    private void timedateDisplay(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM dd, yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");

        datedisplayLabel.setText(dateFormat.format(new Date()));

        Timer timer = new Timer(1000, (e) -> {
            Date now = new Date();
            timedisplayLabel1.setText(timeFormat.format(now));
        });
        timer.start();
    }
    
    public void loadProfilePicture() {
        try {
           
            String sql = "SELECT profile_picture FROM users WHERE id = ?";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            
            String currentUserId = UserSession.getInstance().getUserId();
            String idNumber = currentUserId.split(",")[0].split(":")[1];

            int userId = Integer.parseInt(idNumber);
            pstmt.setInt(1, userId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                byte[] imageData = rs.getBytes("profile_picture");
                if (imageData != null) {
                    ImageIcon imageIcon = new ImageIcon(imageData);
                    Image image = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    lblProfilePic.setIcon(new ImageIcon(image));
                    lblProfilePic.setText("");
                } else {
                    ImageIcon defaultIcon = new ImageIcon(getClass().getResource("/icons/default_profile.jpg"));
                    Image image = defaultIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                    lblProfilePic.setIcon(new ImageIcon(image));
                    lblProfilePic.setText("");
                    
                }
            }
        } catch (SQLException e) {
                    String userName = nameLoggedinLabel.getText();
                        if (userName != null && !userName.isEmpty()) {
                            lblProfilePic.setText(userName.substring(0, 1).toUpperCase());
                            lblProfilePic.setFont(new Font("Verdana", Font.BOLD, 36));
                        }
        }
    }
    
    private void updateRejoinPanelVisibility() {
        if (lobbyCode == null || lobbyCode.isEmpty()) {
            jPanel7.setVisible(false);
            rejoinlobbyButton1.setVisible(false);
        } else {
            jPanel7.setVisible(true);
            existinglobbycodeLabel.setText(lobbyCode);
        }
    }
    
    public void setLobbyCode(String code) {
        this.lobbyCode = code;
        updateRejoinPanelVisibility();
    }

    public String getLobbyCode() {
        return lobbyCode;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_StudentLandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDUHANCE_StudentLandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addfileIcon;
    private javax.swing.JLabel addfriendIcon;
    private javax.swing.JLabel courseLoggedinLabel;
    private javax.swing.JButton createlobbyButton;
    private javax.swing.JLabel datedisplayLabel;
    private javax.swing.JLabel editprofileIcon;
    private javax.swing.JLabel emailLoggedinLabel;
    private javax.swing.JLabel existinglobbycodeLabel;
    private javax.swing.JLabel existinglobbycodeLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    private javax.swing.JButton joinButton;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel nameLoggedinLabel;
    private javax.swing.JPanel panel555;
    private javax.swing.JButton rejoinlobbyButton;
    private javax.swing.JButton rejoinlobbyButton1;
    private javax.swing.JButton signoutButton;
    private javax.swing.JLabel timedisplayLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JLabel yearlevelLoggedLabel;
    // End of variables declaration//GEN-END:variables
}
