/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

//import java.io.DataInputStream;
//import java.io.DataOutputStream;
//import java.net.ServerSocket;
//import java.net.Socket;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author JED
 */
public class EDUHANCE_Student_Question_Form_Window extends javax.swing.JFrame {
//    static ServerSocket ss;
//    static Socket s;
//    static DataInputStream dis;
//    static DataOutputStream dout;
    private String lobbyCode;
            
    /**
     * Creates new form EDUHANCE_Student_Question_Form_Window
     */
    public EDUHANCE_Student_Question_Form_Window() {
        initComponents();
        
//        try {
//            if (s == null || s.isClosed()){
//                String msgin = "";
//                s = new Socket("127.0.0.1", 1201); // ip address is localhost because it is running in the same computer
//                dis = new DataInputStream(s.getInputStream());
//                dout = new DataOutputStream(s.getOutputStream());
//            
//            }
//        }
//        catch(Exception e){
//            //HANDLE EXCEPTION HERE
//        }
        
        System.out.println("Current UserID in session: " + UserSession.getInstance().getUserId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentquestionBox = new javax.swing.JTextArea();
        leaveButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        icon1 = new javax.swing.JLabel();
        clearallButton2 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(250, 250, 250));
        titleLabel2.setText("EDUHANCE");
        getContentPane().add(titleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        questionLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(250, 250, 250));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Type your question below:");
        getContentPane().add(questionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 20));

        titleLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(250, 250, 250));
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("Student Inquiry System");
        getContentPane().add(titleLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 270, 20));

        studentquestionBox.setColumns(20);
        studentquestionBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentquestionBox.setForeground(new java.awt.Color(102, 102, 102));
        studentquestionBox.setLineWrap(true);
        studentquestionBox.setRows(5);
        studentquestionBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 40));
        jScrollPane1.setViewportView(studentquestionBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 360, 150));

        leaveButton.setBackground(new java.awt.Color(255, 0, 0));
        leaveButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        leaveButton.setForeground(new java.awt.Color(255, 255, 255));
        leaveButton.setText("Cancel");
        leaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(leaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 100, 50));

        submitButton.setBackground(new java.awt.Color(250, 250, 250));
        submitButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(5, 35, 79));
        submitButton.setText("Submit");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, 50));

        icon1.setForeground(new java.awt.Color(255, 255, 255));
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bell_26px.png"))); // NOI18N
        getContentPane().add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 30, 50));

        clearallButton2.setBackground(new java.awt.Color(250, 250, 250));
        clearallButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        clearallButton2.setForeground(new java.awt.Color(5, 35, 79));
        clearallButton2.setText("Clear All");
        clearallButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearallButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearallButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(clearallButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 100, 50));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 650));

        noteLabel.setBackground(new java.awt.Color(51, 255, 51));
        noteLabel.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(250, 250, 250));
        noteLabel.setText("<html>Your Information will be hidden and cannot be viewed based on the Instructor's settings</html>");
        getContentPane().add(noteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 180, 50));

        jPanel1.setBackground(new java.awt.Color(5, 35, 79));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        if (studentquestionBox.getText().equals("")){
            dispose();
        }
        else{
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to cancel?", 
                "Cancel", JOptionPane.OK_CANCEL_OPTION);

            if (result == JOptionPane.OK_OPTION) {
                dispose();
    //            new NewJFrame1().setVisible(true);
            }
        }
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void clearallButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallButton2ActionPerformed
        studentquestionBox.setText("");
        studentquestionBox.requestFocus();
    }//GEN-LAST:event_clearallButton2ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            String msg = studentquestionBox.getText().trim();
            System.out.println("Message content: " + msg);
            if (!msg.isEmpty()) {
                // Get user ID from session
                String userIdStr = UserSession.getInstance().getUserId();
                System.out.println("Raw UserID from session: " + userIdStr);

                // Extract just the numeric ID before the comma
                String[] parts = userIdStr.split(",");
                String cleanUserId = parts[0].replaceAll("[^0-9]", "");
                System.out.println("Cleaned UserID: " + cleanUserId);

                if (!cleanUserId.isEmpty()) {
                    int userId = Integer.parseInt(cleanUserId);
                    System.out.println("Parsed UserID as integer: " + userId);

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/eduhance_db", "root", "");

                    String lobbyQuery = "SELECT lobbyId FROM lobby WHERE lobbyCode = ?";
                    PreparedStatement lobbyStmt = conn.prepareStatement(lobbyQuery);
                    lobbyStmt.setString(1, lobbyCode);
                    ResultSet rs = lobbyStmt.executeQuery();

                    if (rs.next()) {
                        int lobbyId = rs.getInt("lobbyId");
                        String sql = "INSERT INTO inquiry (id, inquiry, lobbyId) VALUES (?, ?, ?)";
                        PreparedStatement pstmt = conn.prepareStatement(sql);
                        pstmt.setInt(1, userId);
                        pstmt.setString(2, msg);
                        pstmt.setInt(3, lobbyId);
                        pstmt.executeUpdate();

                        studentquestionBox.setText("");
                        System.out.println("Message saved successfully");
                        dispose();
                    } else {
                        System.out.println("Current lobby code: " + lobbyCode);
                        JOptionPane.showMessageDialog(this, "Invalid lobby code");
                    }
                    conn.close();
                } 
            }
        } catch (Exception e) {
            System.out.println("Error occurred: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error sending message: " + e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    
    public void setLobbyCode(String code) {
        this.lobbyCode = code;
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_Student_Question_Form_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_Student_Question_Form_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_Student_Question_Form_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_Student_Question_Form_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDUHANCE_Student_Question_Form_Window().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton clearallButton2;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton leaveButton;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextArea studentquestionBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    // End of variables declaration//GEN-END:variables
}
