/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;


/**
 *
 * @author JED
 */
public class EDUHANCE_ProfileWindow extends javax.swing.JFrame {
    private Connection connection;
    private EDUHANCE_StudentLandingPage studentLandingPage;
    
    /**
     * Creates new form EDUHANCE_ProfileWindow
     */
    public EDUHANCE_ProfileWindow(EDUHANCE_StudentLandingPage studentLandingPage) {
        this.studentLandingPage = studentLandingPage;
        initComponents();
        establishDatabaseConnection();
        loadUserData();
    }
    
    private void establishDatabaseConnection() {
        try {
            connection = DatabaseConnection.getConnection();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Database connection failed", 
                "Connection Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        editprofileLabel = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        firstnameLabel1 = new javax.swing.JLabel();
        middlenameField = new javax.swing.JTextField();
        middlenameLabel = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        firstnameLabel2 = new javax.swing.JLabel();
        yearlevelComboBox = new javax.swing.JComboBox<>();
        yearlevelLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        courseField = new javax.swing.JTextField();
        uploadprofilepicButton = new javax.swing.JButton();
        lblProfilePic = new javax.swing.JLabel();
        savechangesButton = new javax.swing.JButton();
        leaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(5, 35, 79));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(5, 35, 79));

        jPanel2.setBackground(new java.awt.Color(33, 78, 114));

        editprofileLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        editprofileLabel.setForeground(new java.awt.Color(255, 255, 255));
        editprofileLabel.setText("Edit Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(editprofileLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(editprofileLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        firstnameField.setBackground(new java.awt.Color(250, 250, 250));
        firstnameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstnameField.setForeground(new java.awt.Color(33, 78, 114));
        firstnameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        firstnameField.setCaretColor(new java.awt.Color(51, 51, 51));
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });

        firstnameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstnameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel1.setText("First Name:");

        middlenameField.setBackground(new java.awt.Color(250, 250, 250));
        middlenameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        middlenameField.setForeground(new java.awt.Color(33, 78, 114));
        middlenameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        middlenameField.setCaretColor(new java.awt.Color(51, 51, 51));
        middlenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameFieldActionPerformed(evt);
            }
        });

        middlenameLabel.setBackground(new java.awt.Color(255, 255, 255));
        middlenameLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        middlenameLabel.setForeground(new java.awt.Color(255, 255, 255));
        middlenameLabel.setText("Middle Name:");

        lastnameField.setBackground(new java.awt.Color(250, 250, 250));
        lastnameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastnameField.setForeground(new java.awt.Color(33, 78, 114));
        lastnameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        lastnameField.setCaretColor(new java.awt.Color(51, 51, 51));
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });

        firstnameLabel2.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstnameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel2.setText("Last Name:");

        yearlevelComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        yearlevelComboBox.setForeground(new java.awt.Color(33, 78, 114));
        yearlevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        yearlevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearlevelComboBoxActionPerformed(evt);
            }
        });

        yearlevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        yearlevelLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        yearlevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearlevelLabel.setText("Year Level:");

        courseLabel.setBackground(new java.awt.Color(255, 255, 255));
        courseLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLabel.setText("Course:");

        courseField.setBackground(new java.awt.Color(250, 250, 250));
        courseField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        courseField.setForeground(new java.awt.Color(33, 78, 114));
        courseField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        courseField.setCaretColor(new java.awt.Color(51, 51, 51));
        courseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseFieldActionPerformed(evt);
            }
        });

        uploadprofilepicButton.setBackground(new java.awt.Color(250, 250, 250));
        uploadprofilepicButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        uploadprofilepicButton.setForeground(new java.awt.Color(5, 35, 79));
        uploadprofilepicButton.setText("<html>Upload <br> Profile Picture</html>");
        uploadprofilepicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadprofilepicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadprofilepicButtonActionPerformed(evt);
            }
        });

        lblProfilePic.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblProfilePic.setForeground(new java.awt.Color(250, 250, 250));
        lblProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfilePic.setText("Profile Picture");
        lblProfilePic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 250), 3));

        savechangesButton.setBackground(new java.awt.Color(139, 125, 20));
        savechangesButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        savechangesButton.setForeground(new java.awt.Color(255, 215, 0));
        savechangesButton.setText("Save Changes");
        savechangesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        savechangesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savechangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesButtonActionPerformed(evt);
            }
        });

        leaveButton.setBackground(new java.awt.Color(255, 0, 0));
        leaveButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        leaveButton.setForeground(new java.awt.Color(255, 255, 255));
        leaveButton.setText("Cancel");
        leaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(uploadprofilepicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middlenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middlenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearlevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearlevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(savechangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstnameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(middlenameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(middlenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstnameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearlevelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearlevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uploadprofilepicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savechangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void middlenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameFieldActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void courseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseFieldActionPerformed

    private void uploadprofilepicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadprofilepicButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg"));
        
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIcon imageIcon = new ImageIcon(fileChooser.getSelectedFile().getPath());
                Image image = imageIcon.getImage().getScaledInstance(260, 260, Image.SCALE_SMOOTH);
                lblProfilePic.setIcon(new ImageIcon(image));
                lblProfilePic.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error loading image!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_uploadprofilepicButtonActionPerformed

    private void savechangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesButtonActionPerformed
        try {
            String userIdString = UserSession.getInstance().getUserId();
            String idNumber = userIdString.split(",")[0].split(":")[1];
            int userId = Integer.parseInt(idNumber);

            String sql = "UPDATE users SET firstName = ?, middleName = ?, lastName = ?, course = ?, yearLevel = ? WHERE id = ?";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, firstnameField.getText());
            pstmt.setString(2, middlenameField.getText());
            pstmt.setString(3, lastnameField.getText());
            pstmt.setString(4, courseField.getText());
            pstmt.setString(5, yearlevelComboBox.getSelectedItem().toString());
            pstmt.setInt(6, userId);

            int rowsAffected = pstmt.executeUpdate();

            ImageIcon icon = (ImageIcon) lblProfilePic.getIcon();
            if (icon != null) {
                byte[] imageData = imageToByteArray(icon.getImage());
                sql = "UPDATE users SET profile_picture = ? WHERE id = ?";
                pstmt = connection.prepareStatement(sql);
                pstmt.setBytes(1, imageData);
                pstmt.setInt(2, userId);
                pstmt.executeUpdate();
            }

            if (rowsAffected > 0) {
                sql = "SELECT firstName, middleName, lastName, email, course, yearLevel FROM users WHERE id = ?";
                pstmt = connection.prepareStatement(sql);
                pstmt.setInt(1, userId);
                ResultSet rs = pstmt.executeQuery();
                
                if (rs.next()) {
                    String name = rs.getString("firstName");
                    String email = rs.getString("email");
                    String course = rs.getString("course");
                    String yearLevel = rs.getString("yearLevel");

                    studentLandingPage.setUserData(name, email, course, yearLevel);
                }
                
//                JOptionPane.showMessageDialog(this, "Profile updated successfully!");
                studentLandingPage.loadProfilePicture();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No user found with ID: " + userId);
            }

        } catch (SQLException e) {
            System.out.println("SQL Error: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            System.out.println("Number Format Error: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Invalid user ID format", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savechangesButtonActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        EDUHANCE_StudentLandingPage.instance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void yearlevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearlevelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearlevelComboBoxActionPerformed
    private void loadUserData() {
        try {
            String userIdString = UserSession.getInstance().getUserId();
            String idNumber = userIdString.split(",")[0].split(":")[1];
            int userId = Integer.parseInt(idNumber);

            String sql = "SELECT firstName, middleName, lastName, course, yearLevel FROM users WHERE id = ?";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            pstmt.setInt(1, userId);

            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                firstnameField.setText(rs.getString("firstName"));
                middlenameField.setText(rs.getString("middleName"));
                lastnameField.setText(rs.getString("lastName"));
                courseField.setText(rs.getString("course"));

            }

        } catch (SQLException e) {
            System.out.println("Error loading user data: " + e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error loading user data", 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private byte[] imageToByteArray(Image image) {
        try {
            BufferedImage bi = new BufferedImage(
                image.getWidth(null), 
                image.getHeight(null), 
                BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = bi.createGraphics();
            g2.drawImage(image, 0, 0, null);
            g2.dispose();

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "jpg", baos);
            return baos.toByteArray();
        } catch (IOException e) {
            return null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_ProfileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_ProfileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_ProfileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUHANCE_ProfileWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new EDUHANCE_ProfileWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseField;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel editprofileLabel;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameLabel1;
    private javax.swing.JLabel firstnameLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JButton leaveButton;
    private javax.swing.JTextField middlenameField;
    private javax.swing.JLabel middlenameLabel;
    private javax.swing.JButton savechangesButton;
    private javax.swing.JButton uploadprofilepicButton;
    private javax.swing.JComboBox<String> yearlevelComboBox;
    private javax.swing.JLabel yearlevelLabel;
    // End of variables declaration//GEN-END:variables
}
