/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduhance_student_inquiry_system_mainfile;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import javax.swing.JOptionPane;


/**
 *
 * @author JED
 */
public class REGISTER_EDH2 extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER_EDH2
     */
    public REGISTER_EDH2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        firstnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        confirmpasswordField = new javax.swing.JPasswordField();
        firstnameLabel = new javax.swing.JLabel();
        firstnameLabel1 = new javax.swing.JLabel();
        firstnameLabel2 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        passwordLabel1 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        showpassToggleButton = new javax.swing.JToggleButton();
        showconfirmpassToggleButton = new javax.swing.JToggleButton();
        courseLabel = new javax.swing.JLabel();
        courseField = new javax.swing.JTextField();
        yearlevelLabel = new javax.swing.JLabel();
        middlenameField = new javax.swing.JTextField();
        middlenameLabel = new javax.swing.JLabel();
        yearlevelComboBox = new javax.swing.JComboBox<>();
        studentRadioButton = new javax.swing.JRadioButton();
        instructorRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 35, 35));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 78, 114));

        titleLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel2.setText("EDUHANCE");

        titleLabel3.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("Student Inquiry System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(247, 247, 247))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 90));

        jPanel3.setBackground(new java.awt.Color(5, 35, 79));
        jPanel3.setForeground(new java.awt.Color(35, 35, 35));

        jPanel1.setBackground(new java.awt.Color(33, 78, 114));

        firstnameField.setBackground(new java.awt.Color(250, 250, 250));
        firstnameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        firstnameField.setForeground(new java.awt.Color(33, 78, 114));
        firstnameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        firstnameField.setCaretColor(new java.awt.Color(51, 51, 51));
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });

        emailField.setBackground(new java.awt.Color(250, 250, 250));
        emailField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(33, 78, 114));
        emailField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        emailField.setCaretColor(new java.awt.Color(51, 51, 51));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        lastnameField.setBackground(new java.awt.Color(250, 250, 250));
        lastnameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lastnameField.setForeground(new java.awt.Color(33, 78, 114));
        lastnameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        lastnameField.setCaretColor(new java.awt.Color(51, 51, 51));
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(250, 250, 250));
        passwordField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(33, 78, 114));
        passwordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        passwordField.setCaretColor(new java.awt.Color(51, 51, 51));
        passwordField.setMargin(new java.awt.Insets(10, 6, 2, 6));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        confirmpasswordField.setBackground(new java.awt.Color(250, 250, 250));
        confirmpasswordField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmpasswordField.setForeground(new java.awt.Color(33, 78, 114));
        confirmpasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        confirmpasswordField.setCaretColor(new java.awt.Color(51, 51, 51));
        confirmpasswordField.setMargin(new java.awt.Insets(10, 6, 2, 6));
        confirmpasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordFieldActionPerformed(evt);
            }
        });

        firstnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel.setText("Email:");

        firstnameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstnameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel1.setText("First Name:");

        firstnameLabel2.setBackground(new java.awt.Color(255, 255, 255));
        firstnameLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        firstnameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        firstnameLabel2.setText("Last Name:");

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");

        registerButton.setBackground(new java.awt.Color(250, 250, 250));
        registerButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(5, 35, 79));
        registerButton.setText("Register");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        passwordLabel1.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("Confirm Password:");

        label9.setBackground(new java.awt.Color(255, 255, 255));
        label9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label9.setForeground(new java.awt.Color(102, 102, 255));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("<html><p>Log in with your existing account</p></html>");
        label9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelClicked(evt);
            }
        });

        showpassToggleButton.setBackground(new java.awt.Color(209, 209, 209));
        showpassToggleButton.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        showpassToggleButton.setForeground(new java.awt.Color(66, 255, 255));
        showpassToggleButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        showpassToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpassToggleButton.setFocusPainted(false);
        showpassToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassToggleButtonActionPerformed(evt);
            }
        });

        showconfirmpassToggleButton.setBackground(new java.awt.Color(209, 209, 209));
        showconfirmpassToggleButton.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        showconfirmpassToggleButton.setForeground(new java.awt.Color(66, 255, 255));
        showconfirmpassToggleButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        showconfirmpassToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showconfirmpassToggleButton.setFocusPainted(false);
        showconfirmpassToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showconfirmpassToggleButtonActionPerformed(evt);
            }
        });

        courseLabel.setBackground(new java.awt.Color(255, 255, 255));
        courseLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        courseLabel.setForeground(new java.awt.Color(255, 255, 255));
        courseLabel.setText("Course:");

        courseField.setBackground(new java.awt.Color(250, 250, 250));
        courseField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        courseField.setForeground(new java.awt.Color(33, 78, 114));
        courseField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        courseField.setCaretColor(new java.awt.Color(51, 51, 51));
        courseField.setEnabled(false);
        courseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseFieldActionPerformed(evt);
            }
        });

        yearlevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        yearlevelLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        yearlevelLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearlevelLabel.setText("Year Level:");

        middlenameField.setBackground(new java.awt.Color(250, 250, 250));
        middlenameField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        middlenameField.setForeground(new java.awt.Color(33, 78, 114));
        middlenameField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        middlenameField.setCaretColor(new java.awt.Color(51, 51, 51));
        middlenameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameFieldActionPerformed(evt);
            }
        });

        middlenameLabel.setBackground(new java.awt.Color(255, 255, 255));
        middlenameLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        middlenameLabel.setForeground(new java.awt.Color(255, 255, 255));
        middlenameLabel.setText("Middle Name:");

        yearlevelComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        yearlevelComboBox.setForeground(new java.awt.Color(33, 78, 114));
        yearlevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1st Year", "2nd Year", "3rd Year", "4th Year" }));
        yearlevelComboBox.setEnabled(false);

        studentRadioButton.setBackground(new java.awt.Color(33, 78, 114));
        buttonGroup1.add(studentRadioButton);
        studentRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        studentRadioButton.setForeground(new java.awt.Color(250, 250, 250));
        studentRadioButton.setText("Student");
        studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioButtonActionPerformed(evt);
            }
        });

        instructorRadioButton.setBackground(new java.awt.Color(33, 78, 114));
        buttonGroup1.add(instructorRadioButton);
        instructorRadioButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        instructorRadioButton.setForeground(new java.awt.Color(250, 250, 250));
        instructorRadioButton.setSelected(true);
        instructorRadioButton.setText("Instructor");
        instructorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(middlenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(middlenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(instructorRadioButton)
                                        .addGap(38, 38, 38)
                                        .addComponent(studentRadioButton)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(courseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(courseField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearlevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearlevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showpassToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(confirmpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(showconfirmpassToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentRadioButton)
                    .addComponent(instructorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel1)
                    .addComponent(middlenameLabel)
                    .addComponent(firstnameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(middlenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstnameLabel)
                .addGap(9, 9, 9)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearlevelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearlevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(courseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(showpassToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(showconfirmpassToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmpasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 700));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 460, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void confirmpasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String firstName = firstnameField.getText();
        String middleName = middlenameField.getText();
        String lastName = lastnameField.getText();
        String email = emailField.getText();
        String password = passwordField.getText();
        String confirmPassword = confirmpasswordField.getText();
        String course = courseField.getText();
        String yearLevel = yearlevelComboBox.getSelectedItem().toString();
        String userType = studentRadioButton.isSelected() ? "student" : "instructor";

        
        if(firstName.isEmpty()|| middleName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.",
                                        "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.",
                                    "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.",
                                        "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must have atleast 8 characters.",
                                        "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(studentRadioButton.isSelected() && course.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course is required for students.",
                                        "Registration Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
//        if(studentRadioButton.isSelected() && userType.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Year level is required for students.",
//                                        "Registration Error", JOptionPane.ERROR_MESSAGE);
//            return;
//        }

        try {
            URL url = new URL("http://localhost/EDUHANCE/register_EDUHANCE.php");
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);

            String postData = "firstName=" + URLEncoder.encode(firstName, "UTF-8") +
                         "&middleName=" + URLEncoder.encode(middleName, "UTF-8") +
                         "&lastName=" + URLEncoder.encode(lastName, "UTF-8") +
                         "&email=" + URLEncoder.encode(email, "UTF-8") +
                         "&password=" + URLEncoder.encode(password, "UTF-8") +
                         "&course=" + URLEncoder.encode(course, "UTF-8") +
                         "&yearLevel=" + URLEncoder.encode(yearLevel, "UTF-8") +
                         "&userType=" + URLEncoder.encode(userType, "UTF-8");

            try (OutputStream os = conn.getOutputStream()) {
                os.write(postData.getBytes());
            }

            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                response.append(line);
            }

            if (response.toString().contains("\"status\":\"success\"")) {
                JOptionPane.showMessageDialog(this, "Registration successful!",
                                            "Success", JOptionPane.INFORMATION_MESSAGE);
                
                LOGIN_EDH2 loginwin = new LOGIN_EDH2();
                loginwin.setVisible(true);
                
                clearFields();
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "Registration failed. Please try again.",
                                            "Registration Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Connection error: " + e.getMessage() + "\nPlease check if XAMPP is running.",
                                        "Connection Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginLabelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelClicked
        LOGIN_EDH2 loginwin = new LOGIN_EDH2();
        loginwin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginLabelClicked

    private void showpassToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassToggleButtonActionPerformed
        if (showpassToggleButton.isSelected()) {
            passwordField.setEchoChar((char)0);
            showpassToggleButton.setText("✓");
        } else {
            passwordField.setEchoChar('•');
            showpassToggleButton.setText("");
        }
    }//GEN-LAST:event_showpassToggleButtonActionPerformed

    private void showconfirmpassToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showconfirmpassToggleButtonActionPerformed
        if (showpassToggleButton.isSelected()) {
            confirmpasswordField.setEchoChar((char)0);
            showpassToggleButton.setText("✓");
        } else {
            confirmpasswordField.setEchoChar('•');
            showpassToggleButton.setText("");
        }
    }//GEN-LAST:event_showconfirmpassToggleButtonActionPerformed

    private void courseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseFieldActionPerformed

    private void middlenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameFieldActionPerformed

    private void instructorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorRadioButtonActionPerformed
        courseField.setEnabled(false);
        yearlevelComboBox.setEnabled(false);
        
        courseField.setText("");
        yearlevelComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_instructorRadioButtonActionPerformed

    private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed
        courseField.setEnabled(true);
        yearlevelComboBox.setEnabled(true);
        
    }//GEN-LAST:event_studentRadioButtonActionPerformed

    private void clearFields() {
        firstnameField.setText("");
        middlenameField.setText("");
        lastnameField.setText("");
        emailField.setText("");
        passwordField.setText("");
        confirmpasswordField.setText("");
        courseField.setText("");
        yearlevelComboBox.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER_EDH2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER_EDH2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER_EDH2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER_EDH2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER_EDH2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmpasswordField;
    private javax.swing.JTextField courseField;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JLabel firstnameLabel1;
    private javax.swing.JLabel firstnameLabel2;
    private javax.swing.JRadioButton instructorRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label9;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JTextField middlenameField;
    private javax.swing.JLabel middlenameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JButton registerButton;
    private javax.swing.JToggleButton showconfirmpassToggleButton;
    private javax.swing.JToggleButton showpassToggleButton;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JComboBox<String> yearlevelComboBox;
    private javax.swing.JLabel yearlevelLabel;
    // End of variables declaration//GEN-END:variables
}
